*************
WEEK 4, DAY 1
*************

🌟 Exercise 1 : Array Creation and Manipulation
Instructions

Create a 1D NumPy array containing numbers from 0 to 9.

In [2]:
import numpy as np

# Creating a 1D NumPy array
array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("1D Array:", array_1d)

1D Array: [0 1 2 3 4 5 6 7 8 9]


🌟 Exercise 2 : Type Conversion and Array Operations
Instructions

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:
array([3, 2, 0, 1, 2])

In [3]:
float_list = [3.14, 2.17, 0, 1, 2]
float_arr = np.array(float_list)
int_arr = float_arr.astype(int)
print(float_arr)
print(int_arr)
print(f"dtype: {int_arr.dtype}")

[3.14 2.17 0.   1.   2.  ]
[3 2 0 1 2]
dtype: int64


🌟 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions

Create a 3x3 NumPy array with values ranging from 1 to 9.

In [4]:
import numpy as np

array_2d = np.arange(1, 10).reshape(3, 3)

print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [5]:
array_2d = np.random.rand(4, 5)
print(array_2d)

[[0.26959611 0.2874202  0.10933328 0.99170401 0.16151373]
 [0.57044237 0.08441251 0.25095896 0.06093216 0.46008604]
 [0.21981653 0.46616229 0.22180117 0.4346409  0.81771976]
 [0.10095623 0.83794345 0.84615127 0.81035283 0.90939964]]



🌟 Exercise 5 : Indexing Arrays
Instructions

Select the second row from a given 2D NumPy array.

In [6]:
import numpy as np

arr_2d = np.arange(1, 13).reshape(3, 4)

second_row = arr_2d[1,:]

print(second_row)

[5 6 7 8]


🌟 Exercise 6 : Reversing elements
Instructions

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [7]:
import numpy as np

array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

reversed_array_1d = array_1d[::-1]
print(reversed_array_1d)

[9 8 7 6 5 4 3 2 1 0]


🌟 Exercise 7 : Identity Matrix
Instructions

Create a 4x4 identity matrix using NumPy.

In [8]:
import numpy as np

id_matrix = np.eye(4)

print("4x4 identity:")
print(id_matrix)

4x4 identity:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


🌟 Exercise 8 : Simple Aggregate Funcs
Instructions

Find the sum and average of a given 1D array.

In [12]:
import numpy as np

array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

total = array_1d.sum()
average = array_1d.mean()

print("Sum: ", total)
print("Average: ", average)

Sum:  45
Average:  4.5



🌟 Exercise 9 : Create Array and Change its Structure
Instructions

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [13]:
import numpy as np

array_1d = np.arange(1,21)

matrix = array_1d.reshape(4,5)

print(matrix)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]



🌟 Exercise 10 : Conditional Selection of Values
Instructions

Extract all odd numbers from a given NumPy array.

In [14]:
import numpy as np

array_1d = np.array([0,1,2,3,4,5,6,7,8,9])

odd_numbers = array_1d[array_1d % 2 == 1]

print(odd_numbers)

[1 3 5 7 9]
